version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: medigram-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=medigram-pass

volumes:
  mongodata: