name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm build

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/demo/
          remote_host: ec2-54-197-61-157.compute-1.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.DEMO_KEY }}"